// Board & Leadership page content.

export const board = {
  hero: {
    eyebrow: "Board & Leadership",
    title: "Local leaders, volunteering their time for our neighbors.",
    body: "Our board of directors is made up of people who live, work, and serve in Morgan and Weber Counties. Every member volunteers their time and expertise — no board member is compensated.",
  },

  directorsHeading: {
    eyebrow: "Directors",
    title: "Meet the board",
  },

  directors: [
    {
      name: "Mark Chamberlain",
      role: "Board President",
      affiliation: "Ascent Credit Union",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_1f0a88d0482446019a84641c95bff4c7~mv2.jpg",
    },
    {
      name: "Paul Miner",
      role: "Board Vice President",
      affiliation: "Mountain America Credit Union",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_262c3c29acbe4120aeaf9f02c1922ed3~mv2.jpg",
    },
    {
      name: "Lorna Carter",
      role: "Board Treasurer",
      affiliation: "Wasatch Peaks Credit Union",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_2628b20f87ca456a9fe21eb5beeb183c~mv2.jpg",
    },
    {
      name: "Barrett Bonella",
      role: "Associate Professor of Social Work",
      affiliation: "Weber State University",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_79a097e1aa1b40979730551e9857e143~mv2.jpeg",
    },
    {
      name: "Dawn Harold, M.D.",
      role: "Chief Medical Officer",
      affiliation: "Ogden Regional Medical Center",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_430069ab07684dfe88aff359aaad6b17~mv2.jpg",
    },
    {
      name: "Dave Lundstrom",
      role: "Community Representative",
      affiliation: "",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_73723b61644d4d0781c6ded5c0dcae3a~mv2.jpg",
    },
    {
      name: "Sean O'Brien",
      role: "Business Development Liason",
      affiliation: "Northern Utah Rehabilitation Center",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_e709379d18324caf8d77eb75bfe3d345~mv2.png",
    },
    {
      name: "Spence McArthur",
      role: "Executive Vice President",
      affiliation: "Wasatch Peaks Credit Union",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_4f362c5ffcf24c449a05d3cbd91f231a~mv2.jpg",
    },
    {
      name: "Paula Price",
      role: "Community Representative",
      affiliation: "",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_0063d31a590d402c96647a75add6e3b6~mv2.jpg",
    },
    {
      name: "Drew Richards",
      role: "Executive Director",
      affiliation: "The Auberge at North Ogden",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_a56ac53da6804fdcb97f20e339a48325~mv2.jpg",
    },
    {
      name: "Diana Windley",
      role: "Senior Vice President",
      affiliation: "Goldenwest Credit Union",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_9ac88c4164f74054b9968547d951f45a~mv2.jpg",
    },
    {
      name: "Morris Smith",
      role: "Vice President, Commercial Loan Officer",
      affiliation: "DL Evans Bank",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_8cc0717f38d34876a4af412de850e299~mv2.jpg",
    },
    {
      name: "Zach Winegar",
      role: "Senior Vice President of Marketing & Member Engagement",
      affiliation: "America First Credit Union",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_a4932b74f97348e4bb43ae6e965985b9~mv2.jpg",
    },
    {
      name: "Alexis Baker",
      role: "Employee Representative",
      affiliation: "Weber Human Services",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_673de116690a40be88114c86182dd93b~mv2.jpg",
    },
    {
      name: "Kevin Eastman",
      role: "Director, CEO",
      affiliation: "Weber Human Services",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_304278ce95bc43e0a7d42df1a95d235d~mv2.jpg",
    },
    {
      name: "Jed Burton",
      role: "Director, Clinical Services",
      affiliation: "Weber Human Services",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_178bbac493454ddcb5bf26601df08ed6~mv2.jpg",
    },
    {
      name: "Michelle Jenson",
      role: "Director, CFO",
      affiliation: "Weber Human Services",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_d4dfb45014c645a49f8c97cea4964702~mv2.jpg",
    },
    {
      name: "Nobu Iizuka",
      role: "Director, Community and Senior Services",
      affiliation: "Weber Human Services",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_e2779f161ba54abdbc6a719dd8cf7e3b~mv2.jpg",
    },
    {
      name: "Madeline McDonald",
      role: "Director, Foundation",
      affiliation: "Weber Human Services",
      bio: "",
      imageUrl: "https://static.wixstatic.com/media/d4eb6a_c09a156c53774836bd388d7f3fe4a6c5~mv2.webp",
    },
  ],

  joinCta: {
    eyebrow: "Join the board",
    title: "Interested in serving your community?",
    body: "We periodically welcome new directors who bring fresh perspective and a commitment to human services in our region. Reach out to learn about open seats and the nomination process.",
    buttonLabel: "Contact the board",
  },
};
